### ISSUE TITLE
Increasing the file size for image attachments

### ISSUE THREAD

**Issue by f2k1de** [cuties-social/cuties-social-ansible#14]
edit line 77 and 78 of media_attachment.rb:

**Comment by e1mo** [comment]
I'm unable to find anyhting related to this in `app/models/media_attachment.rb`. But in Line 133 and 134 there is:

```ruby
IMAGE_LIMIT = 10.megabytes
VIDEO_LIMIT = 40.megabytes
```

I think we could work with that?

https://github.com/tootsuite/mastodon/blob/85f0e0a606905ecda1322a0f7b65d8b4ff91dd69/app/models/media_attachment.rb#L133.L134

**Comment by f2k1de** [comment]
ja genau das wird es sein. dann ist das nur seit dem was ich da gefunden habe mittlerweile im quellcode verrutscht.

**Comment by n0emis** [comment]
Ich hab da bei meiner letzten Patching-Session schonmal dran rum gepatcht, leider hat das zu Instabiliäten/Abstürzen von sidekiq gefuehrt. Vllt. waere da ein genauer Test um gute Maximalwerte auszuloten notwendig. Anyway, hier der Code:
```yaml
- name: patch image filesize limit
  lineinfile:
    path: "{{ mastodon_path }}/app/models/media_attachment.rb"
    regexp: IMAGE_LIMIT =
    line: "  IMAGE_LIMIT = (ENV['MAX_IMG_SIZE'] || 10).to_i.megabytes"

- name: patch video filesize limit
  lineinfile:
    path: "{{ mastodon_path }}/app/models/media_attachment.rb"
    regexp: VIDEO_LIMIT =
    line: "  VIDEO_LIMIT = (ENV['MAX_VID_SIZE'] || 40).to_i.megabytes"

- name: patch video resolution limit
  lineinfile:
    path: "{{ mastodon_path }}/app/models/media_attachment.rb"
    regexp: MAX_VIDEO_MATRIX_LIMIT =
    line: "  MAX_VIDEO_MATRIX_LIMIT = (ENV['MAX_VID_RESOLUTION'] || 2_304_000).to_i.megabytes"
```
